// Auto-generated from FortiOS 7.4.10 Configuration API

export interface FirewallFirewallSecurityPolicy {
  uuid?: string;
  policyid?: number;
  name?: string;
  comments?: string;
  srcintf?: Record<string, unknown>[];
  dstintf?: Record<string, unknown>[];
  srcaddr?: Record<string, unknown>[];
  "srcaddr-negate"?: 'enable' | 'disable';
  dstaddr?: Record<string, unknown>[];
  "dstaddr-negate"?: 'enable' | 'disable';
  srcaddr6?: Record<string, unknown>[];
  "srcaddr6-negate"?: 'enable' | 'disable';
  dstaddr6?: Record<string, unknown>[];
  "dstaddr6-negate"?: 'enable' | 'disable';
  "internet-service"?: 'enable' | 'disable';
  "internet-service-name"?: Record<string, unknown>[];
  "internet-service-negate"?: 'enable' | 'disable';
  "internet-service-group"?: Record<string, unknown>[];
  "internet-service-custom"?: Record<string, unknown>[];
  "internet-service-custom-group"?: Record<string, unknown>[];
  "internet-service-src"?: 'enable' | 'disable';
  "internet-service-src-name"?: Record<string, unknown>[];
  "internet-service-src-negate"?: 'enable' | 'disable';
  "internet-service-src-group"?: Record<string, unknown>[];
  "internet-service-src-custom"?: Record<string, unknown>[];
  "internet-service-src-custom-group"?: Record<string, unknown>[];
  "internet-service6"?: 'enable' | 'disable';
  "internet-service6-name"?: Record<string, unknown>[];
  "internet-service6-negate"?: 'enable' | 'disable';
  "internet-service6-group"?: Record<string, unknown>[];
  "internet-service6-custom"?: Record<string, unknown>[];
  "internet-service6-custom-group"?: Record<string, unknown>[];
  "internet-service6-src"?: 'enable' | 'disable';
  "internet-service6-src-name"?: Record<string, unknown>[];
  "internet-service6-src-negate"?: 'enable' | 'disable';
  "internet-service6-src-group"?: Record<string, unknown>[];
  "internet-service6-src-custom"?: Record<string, unknown>[];
  "internet-service6-src-custom-group"?: Record<string, unknown>[];
  "enforce-default-app-port"?: 'enable' | 'disable';
  service?: Record<string, unknown>[];
  "service-negate"?: 'enable' | 'disable';
  action?: 'accept' | 'deny';
  "send-deny-packet"?: 'disable' | 'enable';
  schedule?: string;
  status?: 'enable' | 'disable';
  logtraffic?: 'all' | 'utm' | 'disable';
  "learning-mode"?: 'enable' | 'disable';
  nat46?: 'enable' | 'disable';
  nat64?: 'enable' | 'disable';
  "profile-type"?: 'single' | 'group';
  "profile-group"?: string;
  "profile-protocol-options"?: string;
  "ssl-ssh-profile"?: string;
  "av-profile"?: string;
  "webfilter-profile"?: string;
  "dnsfilter-profile"?: string;
  "emailfilter-profile"?: string;
  "dlp-profile"?: string;
  "file-filter-profile"?: string;
  "ips-sensor"?: string;
  "application-list"?: string;
  "voip-profile"?: string;
  "ips-voip-filter"?: string;
  "sctp-filter-profile"?: string;
  "diameter-filter-profile"?: string;
  "virtual-patch-profile"?: string;
  "icap-profile"?: string;
  "cifs-profile"?: string;
  "videofilter-profile"?: string;
  "ssh-filter-profile"?: string;
  "casb-profile"?: string;
  application?: Record<string, unknown>[];
  "app-category"?: Record<string, unknown>[];
  "url-category"?: string;
  "app-group"?: Record<string, unknown>[];
  groups?: Record<string, unknown>[];
  users?: Record<string, unknown>[];
  "fsso-groups"?: Record<string, unknown>[];
}
