// Auto-generated from FortiOS 7.4.10 Configuration API

export interface FirewallFirewallPolicy {
  policyid?: number;
  status?: 'enable' | 'disable';
  name?: string;
  uuid?: string;
  srcintf?: Record<string, unknown>[];
  dstintf?: Record<string, unknown>[];
  action?: 'accept' | 'deny' | 'ipsec';
  nat64?: 'enable' | 'disable';
  nat46?: 'enable' | 'disable';
  "ztna-status"?: 'enable' | 'disable';
  "ztna-device-ownership"?: 'enable' | 'disable';
  srcaddr?: Record<string, unknown>[];
  dstaddr?: Record<string, unknown>[];
  srcaddr6?: Record<string, unknown>[];
  dstaddr6?: Record<string, unknown>[];
  "ztna-ems-tag"?: Record<string, unknown>[];
  "ztna-ems-tag-secondary"?: Record<string, unknown>[];
  "ztna-tags-match-logic"?: 'or' | 'and';
  "ztna-geo-tag"?: Record<string, unknown>[];
  "internet-service"?: 'enable' | 'disable';
  "internet-service-name"?: Record<string, unknown>[];
  "internet-service-group"?: Record<string, unknown>[];
  "internet-service-custom"?: Record<string, unknown>[];
  "network-service-dynamic"?: Record<string, unknown>[];
  "internet-service-custom-group"?: Record<string, unknown>[];
  "internet-service-src"?: 'enable' | 'disable';
  "internet-service-src-name"?: Record<string, unknown>[];
  "internet-service-src-group"?: Record<string, unknown>[];
  "internet-service-src-custom"?: Record<string, unknown>[];
  "network-service-src-dynamic"?: Record<string, unknown>[];
  "internet-service-src-custom-group"?: Record<string, unknown>[];
  "reputation-minimum"?: number;
  "reputation-direction"?: 'source' | 'destination';
  "src-vendor-mac"?: Record<string, unknown>[];
  "internet-service6"?: 'enable' | 'disable';
  "internet-service6-name"?: Record<string, unknown>[];
  "internet-service6-group"?: Record<string, unknown>[];
  "internet-service6-custom"?: Record<string, unknown>[];
  "internet-service6-custom-group"?: Record<string, unknown>[];
  "internet-service6-src"?: 'enable' | 'disable';
  "internet-service6-src-name"?: Record<string, unknown>[];
  "internet-service6-src-group"?: Record<string, unknown>[];
  "internet-service6-src-custom"?: Record<string, unknown>[];
  "internet-service6-src-custom-group"?: Record<string, unknown>[];
  "reputation-minimum6"?: number;
  "reputation-direction6"?: 'source' | 'destination';
  "rtp-nat"?: 'disable' | 'enable';
  "rtp-addr"?: Record<string, unknown>[];
  "send-deny-packet"?: 'disable' | 'enable';
  "firewall-session-dirty"?: 'check-all' | 'check-new';
  schedule?: string;
  "schedule-timeout"?: 'enable' | 'disable';
  "policy-expiry"?: 'enable' | 'disable';
  "policy-expiry-date"?: string;
  "policy-expiry-date-utc"?: string;
  service?: Record<string, unknown>[];
  "tos-mask"?: string;
  tos?: string;
  "tos-negate"?: 'enable' | 'disable';
  "anti-replay"?: 'enable' | 'disable';
  "tcp-session-without-syn"?: 'all' | 'data-only' | 'disable';
  "geoip-anycast"?: 'enable' | 'disable';
  "geoip-match"?: 'physical-location' | 'registered-location';
  "dynamic-shaping"?: 'enable' | 'disable';
  "passive-wan-health-measurement"?: 'enable' | 'disable';
  "utm-status"?: 'enable' | 'disable';
  "inspection-mode"?: 'proxy' | 'flow';
  "http-policy-redirect"?: 'enable' | 'disable';
  "ssh-policy-redirect"?: 'enable' | 'disable';
  "ztna-policy-redirect"?: 'enable' | 'disable';
  "webproxy-profile"?: string;
  "profile-type"?: 'single' | 'group';
  "profile-group"?: string;
  "profile-protocol-options"?: string;
  "ssl-ssh-profile"?: string;
  "av-profile"?: string;
  "webfilter-profile"?: string;
  "dnsfilter-profile"?: string;
  "emailfilter-profile"?: string;
  "dlp-profile"?: string;
  "file-filter-profile"?: string;
  "ips-sensor"?: string;
  "application-list"?: string;
  "voip-profile"?: string;
  "ips-voip-filter"?: string;
  "sctp-filter-profile"?: string;
  "diameter-filter-profile"?: string;
  "virtual-patch-profile"?: string;
  "icap-profile"?: string;
  "cifs-profile"?: string;
  "videofilter-profile"?: string;
  "waf-profile"?: string;
  "ssh-filter-profile"?: string;
  "casb-profile"?: string;
  logtraffic?: 'all' | 'utm' | 'disable';
  "logtraffic-start"?: 'enable' | 'disable';
  "capture-packet"?: 'enable' | 'disable';
  "auto-asic-offload"?: 'enable' | 'disable';
  "np-acceleration"?: 'enable' | 'disable';
  "webproxy-forward-server"?: string;
  "traffic-shaper"?: string;
  "traffic-shaper-reverse"?: string;
  "per-ip-shaper"?: string;
  nat?: 'enable' | 'disable';
  "pcp-outbound"?: 'enable' | 'disable';
  "pcp-inbound"?: 'enable' | 'disable';
  "pcp-poolname"?: Record<string, unknown>[];
  "permit-any-host"?: 'enable' | 'disable';
  "permit-stun-host"?: 'enable' | 'disable';
  fixedport?: 'enable' | 'disable';
  "port-preserve"?: 'enable' | 'disable';
  ippool?: 'enable' | 'disable';
  poolname?: Record<string, unknown>[];
  poolname6?: Record<string, unknown>[];
  "session-ttl"?: string;
  "vlan-cos-fwd"?: number;
  "vlan-cos-rev"?: number;
  inbound?: 'enable' | 'disable';
  outbound?: 'enable' | 'disable';
  natinbound?: 'enable' | 'disable';
  natoutbound?: 'enable' | 'disable';
  fec?: 'enable' | 'disable';
  wccp?: 'enable' | 'disable';
  ntlm?: 'enable' | 'disable';
  "ntlm-guest"?: 'enable' | 'disable';
  "ntlm-enabled-browsers"?: Record<string, unknown>[];
  "fsso-agent-for-ntlm"?: string;
  groups?: Record<string, unknown>[];
  users?: Record<string, unknown>[];
  "fsso-groups"?: Record<string, unknown>[];
  "auth-path"?: 'enable' | 'disable';
  disclaimer?: 'enable' | 'disable';
  "email-collect"?: 'enable' | 'disable';
  vpntunnel?: string;
  natip?: string;
  "match-vip"?: 'enable' | 'disable';
  "match-vip-only"?: 'enable' | 'disable';
  "diffserv-copy"?: 'enable' | 'disable';
  "diffserv-forward"?: 'enable' | 'disable';
  "diffserv-reverse"?: 'enable' | 'disable';
  "diffservcode-forward"?: string;
  "diffservcode-rev"?: string;
  "tcp-mss-sender"?: number;
  "tcp-mss-receiver"?: number;
  comments?: string;
  "auth-cert"?: string;
  "auth-redirect-addr"?: string;
  "redirect-url"?: string;
  "identity-based-route"?: string;
  "block-notification"?: 'enable' | 'disable';
  "custom-log-fields"?: Record<string, unknown>[];
  "replacemsg-override-group"?: string;
  "srcaddr-negate"?: 'enable' | 'disable';
  "srcaddr6-negate"?: 'enable' | 'disable';
  "dstaddr-negate"?: 'enable' | 'disable';
  "dstaddr6-negate"?: 'enable' | 'disable';
  "service-negate"?: 'enable' | 'disable';
  "internet-service-negate"?: 'enable' | 'disable';
  "internet-service-src-negate"?: 'enable' | 'disable';
  "internet-service6-negate"?: 'enable' | 'disable';
  "internet-service6-src-negate"?: 'enable' | 'disable';
  "timeout-send-rst"?: 'enable' | 'disable';
  "captive-portal-exempt"?: 'enable' | 'disable';
  "decrypted-traffic-mirror"?: string;
  dsri?: 'enable' | 'disable';
  "radius-mac-auth-bypass"?: 'enable' | 'disable';
  "delay-tcp-npu-session"?: 'enable' | 'disable';
  "vlan-filter"?: string;
  "sgt-check"?: 'enable' | 'disable';
  sgt?: Record<string, unknown>[];
}
