// Auto-generated from FortiOS 7.4.10 Configuration API

export interface FirewallFirewallProxyPolicy {
  uuid?: string;
  policyid?: number;
  name?: string;
  proxy?: 'explicit-web' | 'transparent-web' | 'ftp' | 'ssh' | 'ssh-tunnel' | 'access-proxy';
  "access-proxy"?: Record<string, unknown>[];
  "access-proxy6"?: Record<string, unknown>[];
  srcintf?: Record<string, unknown>[];
  dstintf?: Record<string, unknown>[];
  srcaddr?: Record<string, unknown>[];
  poolname?: Record<string, unknown>[];
  poolname6?: Record<string, unknown>[];
  dstaddr?: Record<string, unknown>[];
  "ztna-ems-tag"?: Record<string, unknown>[];
  "ztna-tags-match-logic"?: 'or' | 'and';
  "device-ownership"?: 'enable' | 'disable';
  "internet-service"?: 'enable' | 'disable';
  "internet-service-negate"?: 'enable' | 'disable';
  "internet-service-name"?: Record<string, unknown>[];
  "internet-service-group"?: Record<string, unknown>[];
  "internet-service-custom"?: Record<string, unknown>[];
  "internet-service-custom-group"?: Record<string, unknown>[];
  "internet-service6"?: 'enable' | 'disable';
  "internet-service6-negate"?: 'enable' | 'disable';
  "internet-service6-name"?: Record<string, unknown>[];
  "internet-service6-group"?: Record<string, unknown>[];
  "internet-service6-custom"?: Record<string, unknown>[];
  "internet-service6-custom-group"?: Record<string, unknown>[];
  service?: Record<string, unknown>[];
  "srcaddr-negate"?: 'enable' | 'disable';
  "dstaddr-negate"?: 'enable' | 'disable';
  "service-negate"?: 'enable' | 'disable';
  action?: 'accept' | 'deny' | 'redirect';
  status?: 'enable' | 'disable';
  schedule?: string;
  logtraffic?: 'all' | 'utm' | 'disable';
  "session-ttl"?: number;
  srcaddr6?: Record<string, unknown>[];
  dstaddr6?: Record<string, unknown>[];
  groups?: Record<string, unknown>[];
  users?: Record<string, unknown>[];
  "http-tunnel-auth"?: 'enable' | 'disable';
  "ssh-policy-redirect"?: 'enable' | 'disable';
  "webproxy-forward-server"?: string;
  "webproxy-profile"?: string;
  transparent?: 'enable' | 'disable';
  disclaimer?: 'disable' | 'domain' | 'policy' | 'user';
  "utm-status"?: 'enable' | 'disable';
  "profile-type"?: 'single' | 'group';
  "profile-group"?: string;
  "profile-protocol-options"?: string;
  "ssl-ssh-profile"?: string;
  "av-profile"?: string;
  "webfilter-profile"?: string;
  "emailfilter-profile"?: string;
  "dlp-profile"?: string;
  "file-filter-profile"?: string;
  "ips-sensor"?: string;
  "application-list"?: string;
  "ips-voip-filter"?: string;
  "sctp-filter-profile"?: string;
  "icap-profile"?: string;
  "cifs-profile"?: string;
  "videofilter-profile"?: string;
  "waf-profile"?: string;
  "ssh-filter-profile"?: string;
  "casb-profile"?: string;
  "replacemsg-override-group"?: string;
  "logtraffic-start"?: 'enable' | 'disable';
  comments?: string;
  "block-notification"?: 'enable' | 'disable';
  "redirect-url"?: string;
  "decrypted-traffic-mirror"?: string;
  "detect-https-in-http-request"?: 'enable' | 'disable';
}
