// Auto-generated from FortiOS 7.4.10 Configuration API

export interface FirewallFirewallVendorMacSummary {}

export interface FirewallFirewallVip {
  name?: string;
  id?: number;
  uuid?: string;
  comment?: string;
  type?: 'static-nat' | 'load-balance' | 'server-load-balance' | 'dns-translation' | 'fqdn' | 'access-proxy';
  "server-type"?: 'http' | 'https' | 'imaps' | 'pop3s' | 'smtps' | 'ssl' | 'tcp' | 'udp' | 'ip';
  "dns-mapping-ttl"?: number;
  "ldb-method"?: 'static' | 'round-robin' | 'weighted' | 'least-session' | 'least-rtt' | 'first-alive' | 'http-host';
  "src-filter"?: Record<string, unknown>[];
  "src-vip-filter"?: 'disable' | 'enable';
  service?: Record<string, unknown>[];
  extip?: string;
  extaddr?: Record<string, unknown>[];
  "h2-support"?: 'enable' | 'disable';
  "h3-support"?: 'enable' | 'disable';
  quic?: Record<string, unknown>[];
  nat44?: 'disable' | 'enable';
  nat46?: 'disable' | 'enable';
  "add-nat46-route"?: 'disable' | 'enable';
  mappedip?: Record<string, unknown>[];
  "mapped-addr"?: string;
  extintf?: string;
  "arp-reply"?: 'disable' | 'enable';
  "http-redirect"?: 'enable' | 'disable';
  persistence?: 'none' | 'http-cookie' | 'ssl-session-id';
  "nat-source-vip"?: 'disable' | 'enable';
  portforward?: 'disable' | 'enable';
  status?: 'disable' | 'enable';
  protocol?: 'tcp' | 'udp' | 'sctp' | 'icmp';
  extport?: string;
  mappedport?: string;
  "gratuitous-arp-interval"?: number;
  "srcintf-filter"?: Record<string, unknown>[];
  "portmapping-type"?: '1-to-1' | 'm-to-n';
  realservers?: Record<string, unknown>[];
  "http-cookie-domain-from-host"?: 'disable' | 'enable';
  "http-cookie-domain"?: string;
  "http-cookie-path"?: string;
  "http-cookie-generation"?: number;
  "http-cookie-age"?: number;
  "http-cookie-share"?: 'disable' | 'same-ip';
  "https-cookie-secure"?: 'disable' | 'enable';
  "http-multiplex"?: 'enable' | 'disable';
  "http-multiplex-ttl"?: number;
  "http-multiplex-max-request"?: number;
  "http-multiplex-max-concurrent-request"?: number;
  "http-ip-header"?: 'enable' | 'disable';
  "http-ip-header-name"?: string;
  "outlook-web-access"?: 'disable' | 'enable';
  "weblogic-server"?: 'disable' | 'enable';
  "websphere-server"?: 'disable' | 'enable';
  "ssl-mode"?: 'half' | 'full';
  "ssl-certificate"?: Record<string, unknown>[];
  "ssl-dh-bits"?: '768' | '1024' | '1536' | '2048' | '3072' | '4096';
  "ssl-algorithm"?: 'high' | 'medium' | 'low' | 'custom';
  "ssl-cipher-suites"?: Record<string, unknown>[];
  "ssl-server-algorithm"?: 'high' | 'medium' | 'low' | 'custom' | 'client';
  "ssl-server-cipher-suites"?: Record<string, unknown>[];
  "ssl-pfs"?: 'require' | 'deny' | 'allow';
  "ssl-min-version"?: 'ssl-3.0' | 'tls-1.0' | 'tls-1.1' | 'tls-1.2' | 'tls-1.3';
  "ssl-max-version"?: 'ssl-3.0' | 'tls-1.0' | 'tls-1.1' | 'tls-1.2' | 'tls-1.3';
  "ssl-server-min-version"?: 'ssl-3.0' | 'tls-1.0' | 'tls-1.1' | 'tls-1.2' | 'tls-1.3' | 'client';
  "ssl-server-max-version"?: 'ssl-3.0' | 'tls-1.0' | 'tls-1.1' | 'tls-1.2' | 'tls-1.3' | 'client';
  "ssl-accept-ffdhe-groups"?: 'enable' | 'disable';
  "ssl-send-empty-frags"?: 'enable' | 'disable';
  "ssl-client-fallback"?: 'disable' | 'enable';
  "ssl-client-renegotiation"?: 'allow' | 'deny' | 'secure';
  "ssl-client-session-state-type"?: 'disable' | 'time' | 'count' | 'both';
  "ssl-client-session-state-timeout"?: number;
  "ssl-client-session-state-max"?: number;
  "ssl-client-rekey-count"?: number;
  "ssl-server-renegotiation"?: 'enable' | 'disable';
  "ssl-server-session-state-type"?: 'disable' | 'time' | 'count' | 'both';
  "ssl-server-session-state-timeout"?: number;
  "ssl-server-session-state-max"?: number;
  "ssl-http-location-conversion"?: 'enable' | 'disable';
  "ssl-http-match-host"?: 'enable' | 'disable';
  "ssl-hpkp"?: 'disable' | 'enable' | 'report-only';
  "ssl-hpkp-primary"?: string;
  "ssl-hpkp-backup"?: string;
  "ssl-hpkp-age"?: number;
  "ssl-hpkp-report-uri"?: string;
  "ssl-hpkp-include-subdomains"?: 'disable' | 'enable';
  "ssl-hsts"?: 'disable' | 'enable';
  "ssl-hsts-age"?: number;
  "ssl-hsts-include-subdomains"?: 'disable' | 'enable';
  monitor?: Record<string, unknown>[];
  "max-embryonic-connections"?: number;
  color?: number;
  "ipv6-mappedip"?: string;
  "ipv6-mappedport"?: string;
  "one-click-gslb-server"?: 'disable' | 'enable';
  "gslb-hostname"?: string;
  "gslb-domain-name"?: string;
  "gslb-public-ips"?: Record<string, unknown>[];
}
